### PR TITLE
Decrease overall latency

### PR DESCRIPTION
**Pull request by ford-prefect**
I'm starting with the jitterbuffer for now. More to come as I find more sources of latency (including interaudio*).

### CODE REVIEW

**Comment by superdump** [comment]
This is fine but please wait until I push up a change I have to make the jitter buffer latency a property on the session and then I change the default value to 50ms.

**Comment by ford-prefect** [comment]
Sounds good. Does it make sense to perhaps have the property be something like: OwrTransportAgent -> OwrMediaSession -> rtpjitterbuffer? I'd imagine a typical application would want to tune this globally for the transport agent rather than for each media session.

**Comment by superdump** [comment]
Probably, yes. :smile:

**Comment by sdroege** [comment]
50ms seems sensible but really add a property for this. Someone running owr on 3G probably wants higher values, and even for wifi I already saw jitter of more than 50ms :smile:

**Comment by superdump** [comment]
I think wifi is actually the worst offender in my experience. But then I've also been testing in areas with overcrowded wifi. :smile: Anyway, like I said, I have patches for this that I will push up next week so you don't need to spend more time on it for now.

**Comment by sdroege** [comment]
See #240 which is related

**Comment by superdump** [comment]
Landed my version of this patch (which has it as a property with 50ms as default.) I agree that we need to add a property to OwrTransportAgent to control all sessions in one fell swoop. With a bit of property binding I guess. Closing this and creating an issue for that.

**Pull request closed without merging**
