### PR TITLE
Attempt to fix protocol to "UDP/TLS" but falling back to only "RTP/SA…

### PR DESCRIPTION
**Pull request by stefhak**
…VPF". This is the way newer versions of Chrome/FF behave.

### CODE REVIEW

**Comment by stefhak** [comment]
or if @superdump or @stefanalund wants to take a look

**Comment by stefanalund** [comment]
How would I verify this is "working"?

**Comment by superdump** [comment]
@stefanalund - I think you would have to do a call between Chrome/Firefox and OWR using bridge, initiate from Chrome/Firefox, check the SDP for UDP/TLS etc and then check the response SDP.

**Comment by stefhak** [comment]
yes, try different versions of Chrome/FF, and different roles of OWR. You should see that if OWR starts (offers) it puts UDP/TLS/RTP/SAVPF if the offer, but if the answer has RTP/SAVPF owr falls back to that in subsequent offers. If the answer has UDP/TLS/RTP/SAVPF owr will maintain that for future offers.
Likewise if Chrome/FF is offerer, owr will follow its pattern (answer with the same sting as the offerer uses)

**Comment by stefhak** [comment]
I've tested against FF and Chrome, and this seems to work. IMO we should merge to be up to date.

**Pull request closed without merging**
