### PR TITLE
Removing RTX for h264 from SDP as Chrome does not work correctly with…

### PR DESCRIPTION
**Pull request by stefhak**
… it. Removes problems with freezing remote video (sent from Chrome Canary using h264) on owr.

### CODE REVIEW

**Comment by sdroege** [comment]
Is this debugged already and reported to Chrome? Or to GStreamer if it's a problem with the RTX handling there?

**Comment by stefhak** [comment]
I've filed a Chrome bug: https://bugs.chromium.org/p/webrtc/issues/detail?id=5810
I've not dug deep into it as h264 _with_ RTX works fine between FF and owr.

**Comment by stefhak** [comment]
@sdroege @superdump @stefanalund I think someone should merge this as it creates problems with h264 interop with Chrome. We can in parallel investigate the reasons.

**Comment by sdroege** [comment]
Sure, I just wanted to be sure that the real problem is tracked somewhere and not just forgotten :)

**Pull request merged**
