### PR TITLE
Make overlay video rendering opt-out

### PR DESCRIPTION
**Pull request by stefanalund**

### CODE REVIEW

**Comment by stefhak** [comment]
LGTM.

**Comment by stefanalund** [comment]
There are different opinions whether "native" video rendering on Bowser https://github.com/EricssonResearch/bowser/pull/66 should be opt-in or opt-out. @pererikb thinks opt-in while me and @superdump are in the opt-out camp (due to the massive performance increase).

Thoughts @stefhak?

**Comment by stefanalund** [comment]
Comparison: https://www.youtube.com/watch?v=87isHPwwUpE

**Comment by stefhak** [comment]
Watching the video brings me to the opt-out camp. I think that developers that find that CSS styling does not work as expected any more will dig into it and understand how to fix it, but bad rendering performance out of the box can make people not trying openwebrtc in the first place.

**Comment by pererikb** [comment]
The question is really whether we want to support applications not specifically targeting Bowser, since overlay rendering imposes certain restrictions that are likely to break them, in some cases the video will not be visible at all, or visible when it should be hidden. Developers targeting Bowser can easily opt-in and then make any changes required for overlay rendering to work with their applications. What we could do is to add a setting in Bowser to force overlay rendering so that users can test how well it works with unmodified applications.

**Comment by stefhak** [comment]
@pererikb your last proposal sounds like a good middle way!

**Comment by stefanalund** [comment]
I agree that it sounds like a good compromise @stefhak @pererikb. One question though: how do we control that from the app when it currently requires a change in OpenWebRTC?

**Comment by pererikb** [comment]
One way could be to toggle navigator.__owrVideoOverlaySupport between "enabled" and "forced".

**Comment by stefanalund** [comment]
OK. I will add a setting in Bowser for toggling this. The web developer should in my view have the possibility to enforce use of non-overlay rendering (if they know it breaks their app for example). This PR makes that possible through applying the class `owr-no-overlay-video` to the `<video>` element.

@pererikb, do you think we can merge this PR then?

**Pull request closed without merging**
