### PR TITLE
Add a URI source

### PR DESCRIPTION
**Pull request by ford-prefect**
This is based on @superdump's work in PR #436 with some fixes for audio to just work, and a new argument to test-send-receive to use a URI instead of webcam/mic.

### CODE REVIEW

**Comment by nbermudezs** [comment]
I was re-compiling for Linux after this was merged and I'm getting this error:
```
test_utils.c: In function ‘bus_message_print_callback’:
test_utils.c:123:9: error: format ‘%p’ expects argument of type ‘void *’, but argument 3 has type ‘struct OwrMessageOrigin *’ [-Werror=format=]
         origin_name = g_strdup_printf("%s<%p>", G_OBJECT_CLASS_NAME(origin), origin);
         ^
cc1: all warnings being treated as errors
make[2]: *** [test_uri-test_utils.o] Error 1
make[2]: Leaving directory `/home/ubuntu/cerbero/sources/linux_x86_64/openwebrtc-0.3.0/tests'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ubuntu/cerbero/sources/linux_x86_64/openwebrtc-0.3.0'
make: *** [all] Error 2
Running command 'make'
```

I bypassed it by just casting `origin` to (void *). Is that the right way to do it?
I'm commenting here because it was working yesterday before this PR was merged.

**Comment by superdump** [comment]
That seems like an oversensitive warning. Do you get issues elsewhere in the code or only for that instance?

**Comment by ford-prefect** [comment]
I saw this as well on Fedora 22, and fixed it locally with that type cast.
Isn't really related to this PR. As @superdump points out, seems to be an
oversensitive compiler (flags?) problem.

**Comment by nbermudezs** [comment]
@superdump only there, but after I added the type cast and retried the build I get this
```
[(36/37) openwebrtc -> post_install ]
***** Error running 'package' command:
Recipe 'openwebrtc' failed at the build step 'post_install'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "/home/ubuntu/cerbero/recipes/openwebrtc.recipe", line 251, in post_install
    f.write(self.owr_version_id)
AttributeError: 'Recipe' object has no attribute 'owr_version_id'
```

@ford-prefect Did this happen to you as well?

**Comment by superdump** [comment]
Odd. Someone else saw that recently. Try running cerbero with the `buildone openwebrtc` command.

**Comment by nbermudezs** [comment]
`buildone openwebrtc` worked, at least the `post_install` error is gone. Now for some reason when I try to build for Android it keeps telling me `Exception: Please update your openwebrtc build for the host linux; it's out of date` even after I fetched the updated code and reran the build for Linux. I'll try a clean build in little while.

**Comment by nbermudezs** [comment]
Everything seems ok after a build from scratch. Got the same error when building for Android but `buildone openwebrtc` worked as well. Thanks for the help.

**Comment by superdump** [comment]
:+1:

**Pull request closed without merging**
