### PR TITLE
libopenwebrtc-gst library 

### PR DESCRIPTION
**Pull request by philn**
This new library contains 2 OwrMediaRenderers allowing application developers to override audio and video sinks used for rendering and one OwrMediaSource class.

### CODE REVIEW

**Comment by philn** [comment]
Ok but if it's disabled by default what should I do about the self-view test?

**Comment by superdump** [comment]
Split it into a test-gst-io or something maybe?

**Comment by philn** [comment]
Here it is, much better indeed with a new test :)

**Comment by superdump** [comment]
This basically looks good to me. Now we need a separate openwebrtc-gst package in cerbero that somehow enables a owr-gst variant that copies in all the necessary gst API and enables the owr-gst lib in openwebrtc so that people can optionally build and install this if they know what they're doing.

**Pull request closed without merging**
