### PR TITLE
Move remaining Cerbero OWRTC patches to upstream

### PR DESCRIPTION
**Pull request by nirbheek**
1) Replace ercolorspace with videoconvert everywhere
2) configure.ac changes to add device-specific cflags/libs for Android and iOS (frameworks, GNU C++ STL, etc)

### CODE REVIEW

**Comment by sdroege** [comment]
Note that this will (most likely!) break the build scripts :) Unless they are changed accordingly too

**Comment by nirbheek** [comment]
Also note that build scripts are already completely broken since the DTLS change in master; see #266.

**Comment by superdump** [comment]
Can we not use the ercolorspace patch until something better is done? That is, I feel like something that works well on armv7/armv7s should be retained until there is a good replacement.

**Comment by nirbheek** [comment]
@superdump The PR now only contains the build-related changes. We can look at the ercolorspace/videoconvert stuff separately. :)

**Comment by Rugvip** [comment]
:+1:

**Pull request merged**
