### PR TITLE
Updated to generate ssrc's, ssrc-group's and cname in mediadesc at createOffer/Answer.

### PR DESCRIPTION
**Pull request by stefhak**
Is related to Issue #62 . Note that an update should be made once https://github.com/pererikb/openwebrtc/commit/f591b67a9eaee207ddd9d383a8b08c2bf8666125 has made it into OWR - the current version hardcodes cname.

An update to peerhandler will be done.

### CODE REVIEW

**Comment by stefhak** [comment]
This seems to work fine now. Any reason why we should not merge?

**Comment by superdump** [comment]
It needs rebasing on top of master. Why is there a merge commit?

**Comment by stefhak** [comment]
The merge commit was to get P-E randomString that accepts a length argument in.

**Comment by superdump** [comment]
Ok, but the process we follow then is to rebase the branch on top of updated master. Can you do that instead please? Then I'll merge it.

I started rebasing it myself but without looking more closely, there were some conflicts that weren't obvious for me to resolve but that you as implementer should be able to. Shout if you need help.

**Comment by stefhak** [comment]
> 14 Jun 2015 kl. 20:24 skrev Robert Swain <notifications@github.com>:
> 
> Ok, but the process we follow then is to rebase the branch on top of updated master. Can you do that instead please? Then I'll merge it.
> 
I'll fix that.

**Pull request closed without merging**
