### PR TITLE
replace gst_object_default_deep_notify with a less verbose _owr_deep_notify that uses log level info

### PR DESCRIPTION
**Pull request by Rugvip**
There was a bit too much g_print spam :no_mouth:

### CODE REVIEW

**Comment by sdroege** [comment]
Yes! :smile: But maybe also put them into their own debug category

**Comment by superdump** [comment]
Did you write _owr_deep_notify yourself from scratch or is it copied from LGPL GStreamer code?

**Comment by Rugvip** [comment]
It's a heavily modified version of the original function, you might recognise some of the variable names and the error string :p

**Comment by Rugvip** [comment]
Btw, about the debug category, we're planning to do some overall improvements in that area, so we might as well wait until we have av overview and find some names that make sense.

**Comment by Rugvip** [comment]
Btw, about the debug category, we're planning to do some overall improvements in that area, so we might as well wait until we have av overview and find some names that make sense.

**Comment by superdump** [comment]
I agree about the debug category. We'll be fixing that properly everywhere soon and certain decisions will need to be made before we can do it so I am OK with deferring that until later.

I had a look at the implementation of gst_object_default_deep_notify() - it both looks like it can only be implemented in a small set of ways using standard GLib functions and _owr_deep_notify is indeed not even close to a copy and paste.

What do you think @sdroege? Looking at git blame for those lines, it was implemented in 2002 by Wim and is mostly untouched since then apart from a couple of minor bug fixes.

**Comment by sdroege** [comment]
Seems ok to me

**Comment by superdump** [comment]
Right, I don't feel like it's copyrightable either and I agree completely that in general code should not be copied and modified unless it is going to retain the original license. I'll land this.

**Pull request closed without merging**
