### PR TITLE
owr: Use a more recent base time

### PR DESCRIPTION
**Pull request by pererikb**

### CODE REVIEW

**Comment by sdroege** [comment]
This is not going to break anything, but it's a workaround for bugs elsewhere if something can't deal with high running times.

What are the problems?

**Comment by tp-m** [comment]
I'm guessing it relates to that gint64 -> gint issue we talked about on IRC the other day?

http://cgit.freedesktop.org/gstreamer/gst-plugins-base/tree/gst-libs/gst/audio/gstaudiobasesrc.c#n927

**Comment by superdump** [comment]
Yes, I believe it relates to that issue.

**Comment by pererikb** [comment]
This patch also improves the readability of the logs, in my opinion

0:00:03.992874000
0:00:04.168808000

is easier to read than

400037:59:47.696667000
400037:59:47.889671000

so I think we should still consider it

**Comment by sdroege** [comment]
That's a valid point, but I would prefer to do that only after the integer overflow problem is fixed. You're just hiding the problem otherwise, and it will probably appear again sooner or later.

**Comment by sdroege** [comment]
FWIW, I think this should just be merged for now as it a) works around the problem and b) makes debug logs a bit nicer to read. Fixing the underlying bug is a bit more complicated and needs further thoughts :)

**Comment by superdump** [comment]
OK. thanks.

**Comment by sdroege** [comment]
I think I also understood why this is mostly a problem on OSX/iOS. I assume we don't get a monotonic clock there, or at least the monotonic clock does not start at 0 when the system starts up, like it does on Linux. So the clock values are always incredibly high on OSX/iOS but relatively small on Linux. In the end things would then work half of the days on OSX/iOS (whenever we have a date that truncated to 32 bits has the sign bit unset). Funny bug

**Comment by sdroege** [comment]
Remaining bug tracked here https://bugzilla.gnome.org/show_bug.cgi?id=754180

**Comment by bramoosterhuis** [comment]
Hi,

Maybe worth to mention. After this commit I got build errors regarding array sizes while cross compiling for the RPi2. Google was pointing me in the direction of 32-64bit differences. However for now I just skip the "if statement" for a RPI so the function will always return 0 as a owr_base_time and it works fine again. 

https://github.com/Metrological/openwebrtc/commit/72d306ac4f226cc5fc7698f87eae6e3ba79e245b

Details: 
owr.c:400:40: error: size of array '_GStaticAssertCompileTimeAssertion_0' is negative
     if (g_once_init_enter(&owr_base_time)) {
                                        ^
owr.c:400:176: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
     if (g_once_init_enter(&owr_base_time)) {

owr.c:400:244: error: size of array '_GStaticAssertCompileTimeAssertion_1' is negative
     if (g_once_init_enter(&owr_base_time)) {
                                                                                                                                                                                                                                                   
owr.c:404:40: error: size of array '_GStaticAssertCompileTimeAssertion_2' is negative
         g_once_init_leave(&owr_base_time, base_time);

**Comment by superdump** [comment]
Argh. `g_once_init_leave` take a gsize as the second argument which is unsigned long - https://developer.gnome.org/glib/stable/glib-Basic-Types.html#gsize and so can be 32-bit or 64-bit depending on the platform and compiler choice so we can't use the guint64 GstClockTime for this. Maybe instead we can use appropriate more flexible protection or a separate variable for the testing and just set the value inside that code block or something.

**Comment by ShGup** [comment]
Hi,
@bramoosterhuis  @superdump :
 I am facing the same build error as you mentioned. 

owr.c:400:9: error: '_GStaticAssertCompileTimeAssertion_0' declared as an array with a negative size
    if (g_once_init_enter(&owr_base_time)) {


1) What is the workaround you applied to get around this?
2) Is there an open issue for this?

**Comment by superdump** [comment]
Two options have been suggested, I just haven't got to implementing the change and testing it yet.

1. Move the g_once_init_enter code to owr_init where it will only be run once anyway
2. Just use a static GMutex instead

There isn't an open issue but unless someone else makes a patch for it, I will soon

**Comment by ShGup** [comment]
Thanks.

**Pull request closed without merging**
