### PR TITLE
local: schedule _set_source, _register, and _unregister on the main thread

### PR DESCRIPTION
**Pull request by Rugvip**
I left out owr_{audio,video}_renderer_constructed since those will never result in any large amount of work.

### CODE REVIEW

**Comment by Rugvip** [comment]
Fixes #253

**Comment by Rugvip** [comment]
Verified with tests and openwebrtc-daemon on OS X, and NativeCall example on Android

**Comment by superdump** [comment]
Looks good.

**Comment by superdump** [comment]
Merged.

**Pull request closed without merging**
