### PR TITLE
Build error with clang

### PR DESCRIPTION
**Pull request by ossy-szeged**
EricssonResearch/openwebrtc#420

### CODE REVIEW

**Comment by sdroege** [comment]
Why not just remove the additional parenthesis?

**Comment by superdump** [comment]
I think that could start a compiler war, possibly. I seem to remember that gcc wants you to add parentheses around certain expressions and it seems that clang wants you to not.

**Comment by ossy-szeged** [comment]
We got this warning for this line: if (GST_PAD_IS_SRC (pad)) , where
GST_PAD_IS_SRC is a macro and the preprocessed code is:
if (((((GstPad)(pad))->direction) == GST_PAD_SRC))

Removing parenthesis from a macro definition is 
unsafe, just think about the following example.
#define FOO(a) a+1
y*FOO(x) means y*a+1 , but you would like to see y*(a+1)

Of course we could remove the other parenthesis,
but "if GST_PAD_IS_SRC (pad)" would be very ugly.

**Comment by sdroege** [comment]
Sounds like Apple's clang again being stupid, so let's work around it that way.

**Comment by philn** [comment]
So can this be merged as-is or an update is needed?

**Pull request closed without merging**
