### PR TITLE
tests: Add a test client that connects to demo.openwebrtc.io

### PR DESCRIPTION
**Pull request by pererikb**

### CODE REVIEW

**Comment by stefanalund** [comment]
Wouldn't this be possible to use for a native iOS app @Rugvip?

**Comment by Rugvip** [comment]
It would work, but I don't think it's a very good example for iOS / OS X development, Objective-C or Swift is the way to go imo.

**Comment by superdump** [comment]
Soooo much code to parse JSON. :sob: Interesting. Merged.

**Comment by sdroege** [comment]
It would be more without json-glib ;)

You might consider creating serializable GObjects for these things, that way you could get serialization/deserialization of JSON automagically and could handle the things like normal GObjects with GObject properties.

**Pull request closed without merging**
