### PR TITLE
java binding: added types needed by datachannel and rtcp stats, and some other fixes

### PR DESCRIPTION
**Pull request by Rugvip**
The datachannel bits haven't been verified yet, but the rest has. All of it builds and works with all pre-datachannel features.

### CODE REVIEW

**Comment by Rugvip** [comment]
Afaik it's the only option, since java only has signed types. I think we'll run into bigger troubles if we map between types with different size.

**Comment by nirbheek** [comment]
Yeah, was looking at how only the latest JDK has support for unsigned types, and that's not available on Android of course. I don't understand how mapping, say, unsigned short to signed int would cause problems. What will go wrong?

**Comment by Rugvip** [comment]
If you have an array of values the size will be incorrect. For a single value it might get truncated without warning.

**Comment by sdroege** [comment]
Mapping between signed and unsigned of the same size will cause problems if values are outside the positive range of the signed integer.

Mapping between signed type and unsigned type of a bigger size will generally work, but has the size problem for arrays @Rugvip just mentioned. You would have to add a conversion step.

**Comment by Rugvip** [comment]
How would you want to represent a unsigned parameter to a function in owr? A larger type and a warning if it's too big?

**Comment by sdroege** [comment]
Either that, or a type with the same size and doing range checking before casting.

**Comment by sdroege** [comment]
It's all broken, no matter what you do, unless using the Java 8 unsigned types.

**Comment by Rugvip** [comment]
Verified that the datachannel related changes work as well.

Dunno about the size/unsigned issue, but it's not really related to these changes.
Signed short is the maximum message size for the datachannel anyway

**Pull request closed without merging**
