### PR TITLE
transport_agent: new API to explicitely start the pipeline

### PR DESCRIPTION
**Pull request by philn**
The owr_transport_agent_add_session function is now limited to storing
the session in an internal list. The list is processed by a new
owr_transport_agent_start function which will perform the necessary
operations in one go to prepare the GStreamer pipeline and start
playback.

This change of behavior is needed for the RTP bundling support because
the agent needs to be aware of all the sessions it will manage as soon
as rtpbin starts prerolling.

### CODE REVIEW

**Comment by philn** [comment]
One possible issue with this approach is that calls following the start-up of the agent will basically have no effect. Maybe in this case we could check in _add_session if the pipeline is in PLAYING state and directly add the session.

Anyway please provide feedback about this patch :)

**Comment by philn** [comment]
@superdump @sdroege what do you think about this?

**Comment by superdump** [comment]
From reading what you wrote about the intended functionality and noteworthy limitations, this would seem to degrade the flexibility of transport agent quite a bit. It might be a good idea to take a look at the JSEP spec to see how things like renegotiations are affected by these changes.

https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-17

**Comment by philn** [comment]
The limitations I mention can be addressed already. I'll update the patch... At this point I don't see how the change of behavior would have bad consequences for renegotiations.

**Comment by philn** [comment]
Patch updated :)

**Comment by stefhak** [comment]
@superdump @sdroege @Rugvip any comments?

**Pull request closed without merging**
