### PR TITLE
Update openwebrtc-0.1.pc.in

### PR DESCRIPTION
**Pull request by frozeus**
Headers are located in a "owr" folder inside the include folder

### CODE REVIEW

**Comment by stefanalund** [comment]
Sorry if I missed something, but what is the reason for this change?

**Comment by superdump** [comment]
As in the commit message, when installed, the owr headers are installed to $PREFIX/include/owr and so the pkg-config CFLAGS should point to that path.

**Comment by Rugvip** [comment]
I guess this is just whether we want it to be `#include <owr/owr.h>` etc, or `#include <owr.h>`? In which case I prefer the former.

**Comment by superdump** [comment]
Yes, good point. Me too. That was an active decision as it is similar to gst/gst.h and others.

**Comment by superdump** [comment]
@frozeus : I'm going to reject this as it is intended that applications include owr/owr.h and so on. Thanks for the contribution though. :smile:

**Comment by frozeus** [comment]
No problem, i prefer also #include <owr/owr.h>

**Pull request closed without merging**
