### PR TITLE
Modify assertion to allow for data sessions

### LINKED ISSUE #516: False assertion in on_new_selected_pair when doing data channels?
I'm currently working on getting a data channel between Chrome and native code going. I've successfully gotten the DTLS handshake to complete, but I get these assertions as the channel tries to come up. Looking at https://github.com/EricssonResearch/openwebrtc/blob/master/transport/owr_transport_agent.c#L1990, this should work just fine for data sessions (we only have RTP components, not RTCP, but the code handles it). I think this assertion needs to be changed to IS_SESSION, vs. IS_MEDIA_SESSION.

** (webrtc_dispatcher:26842): CRITICAL **: on_new_selected_pair: assertion 'OWR_IS_MEDIA_SESSION(session)' failed

** (webrtc_dispatcher:26842): CRITICAL **: on_new_selected_pair: assertion 'OWR_IS_MEDIA_SESSION(session)' failed

### PR DESCRIPTION
**Pull request by NCommander**
Resolves #516 
Signed-off-by: Michael Casadevall <michael@mcprohosting.com>

### CODE REVIEW

**Comment by alessandrod** [comment]
Thanks for spotting this! Can you change the check to actually use OWR_IS_SESSION?

**Comment by NCommander** [comment]
Fixed.

**Comment by alessandrod** [comment]
Looks like you changed the wrong function?

**Comment by NCommander** [comment]
And this is the part where I bury my head in the sand, and remember the golden rule of don't git commit when tired. Corrected, and rebased/squished the branch so its just a single commit instead of making history look stupid.

**Comment by alessandrod** [comment]
Committed, thanks!

**Pull request closed without merging**
