### PR TITLE
RTP bundling support

### PR DESCRIPTION
**Pull request by philn**
This pull-request depends on #653 and https://bugzilla.gnome.org/show_bug.cgi?id=772740

### CODE REVIEW

**Comment by philn** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=772740 is now solved :)

**Comment by stefhak** [comment]
Does this PR also address bundling for the data channel?

**Comment by philn** [comment]
Hum no it doesn't. We barely started working on data channel support for WebKit actually :)

**Comment by stefhak** [comment]
Well, I don't see that as a reason for not adding support for media. So I support merging this PR.

**Comment by philn** [comment]
The corresponding API was removed from GStreamer's `rtpbin`. Closing.

**Pull request closed without merging**
