### PR TITLE
Setting sdpMid to '""' instead of 'null' to be Chrome compatible.

### PR DESCRIPTION
**Pull request by stefhak**
Intended to fix issue #163.

### CODE REVIEW

**Comment by superdump** [comment]
I also think it is silly that you cannot assign more than one person. :wink:

Have you tested this and confirmed that it works with all combinations of Chrome, Firefox, OWR?

**Comment by stefhak** [comment]
I've tested - but only by cheating, i.e. change this in the web-application. I can try with this more "native" fix, but from which stage in the build process do I need to build?

**Comment by superdump** [comment]
It's a simple enough change that hacking it in a web application and testing there is OK for me. I'll let @adam-be and @pererikb check whether it's the 'right' fix though. Thanks!

**Comment by stefanalund** [comment]
Seems to work owr->Chrome, owr->FF. Does not affect problem with black video when running owr->or though: https://github.com/EricssonResearch/openwebrtc/issues/168 

:+1:

**Comment by stefanalund** [comment]
I think we can land this.

**Comment by superdump** [comment]
Agreed. I noticed Chrome writes audio / video in this field.

**Comment by stefhak** [comment]
Chrome uses audio and video since that is what they put for the respective a=mid:" attributes in the sdps. (a bit more about mid in https://tools.ietf.org/html/rfc3388). We've not added support for this yet (should be on the to-do list) and hence it should be left as empty string.

**Comment by stefhak** [comment]
@sdroege: why did you close without merging?

**Comment by superdump** [comment]
@stefhak the commit was pushed softly and then sometimes GitHub didn't notice and the PR has to be closed manually. This has been merged.

**Pull request closed without merging**
